# This file is not being used. Container deployments are managed through:
# 1. Initial deployment: terraform/modules/ec2/user-data.sh
# 2. Container restarts: .github/workflows/docker-ops.yml

# See docker-config.tf for container configuration
