version: '3'

services:
  redis:
    image: ${REDIS_IMAGE}
    ports:
      - "6379:6379"
    restart: always

  api:
    image: ${API_IMAGE}
    ports:
      - "8000:80"
    depends_on:
      - redis
    restart: always

  web:
    image: ${WEB_IMAGE}
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: always

  signable:
    image: ${SIGNABLE_IMAGE}
    ports:
      - "8082:80"
    depends_on:
      - api
    restart: always

  email-server:
    image: ${EMAIL_SERVER_IMAGE}
    ports:
      - "8025:5001"
    restart: always

  company-house:
    image: ${COMPANY_HOUSE_IMAGE}
    ports:
      - "8083:80"
    restart: always

  sonarqube:
    image: ${SONARQUBE_IMAGE}
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: ${POSTGRES_IMAGE}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sonarqube
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube
    restart: always

  prometheus:
    image: ${PROMETHEUS_IMAGE}
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: ${GRAFANA_IMAGE}
    ports:
      - "3100:3000"
    depends_on:
      - prometheus
    restart: always
