name: 'Iykons AWS Deploy'

on:
  push:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-aws.yml'
  pull_request:
    paths:
      - 'terraform/**'
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        type: choice
        required: true
        default: 'plan_infra'
        options:
          - plan_infra
          - create_infra
          - destroy_infra

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: 'Terraform AWS'
    runs-on: ubuntu-latest
    if: |
      (github.event_name != 'workflow_dispatch') || 
      (github.event_name == 'workflow_dispatch' && contains(fromJSON('["plan_infra", "create_infra", "destroy_infra"]'), github.event.inputs.action))

    defaults:
      run:
        working-directory: ./terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
        audience: sts.amazonaws.com

    - name: Create S3 bucket for artifacts and state
      run: |
        aws s3api head-bucket --bucket iykonect-aws-parallel 2>/dev/null || \
        aws s3api create-bucket --bucket iykonect-aws-parallel --region us-east-1

    - name: Package and upload code to S3
      if: (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'create_infra')
      run: |
        echo "Packaging repository content..."
        cd $GITHUB_WORKSPACE
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        zip -r repo-content.zip . -x ".git/*" ".github/workflows/*"
        aws s3 cp repo-content.zip s3://iykonect-aws-parallel/code-deploy/repo-content.zip
        echo "DEPLOYMENT_TIMESTAMP=${TIMESTAMP}" >> $GITHUB_ENV
        echo "Repository content uploaded to S3 bucket: s3://iykonect-aws-parallel/code-deploy/repo-content.zip"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.6.6'

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      env:
        TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      run: |
        echo "Generating Terraform plan..."
        terraform plan -no-color -input=false
      continue-on-error: true

    - name: Update Pull Request
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      env:
        PLAN: "${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `
          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
          
          <details><summary>Show Plan</summary>
          
          \`\`\`terraform\n
          ${process.env.PLAN}
          \`\`\`
          
          </details>`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

    - name: Apply Infrastructure Changes
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'create_infra'
      env:
        TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      run: |
        # Always destroy EC2 and related resources first
        terraform destroy -target=module.ec2.aws_instance.main \
                        -target=module.ec2.aws_iam_role.ec2_role \
                        -target=module.ec2.aws_iam_role_policy.s3_access \
                        -target=module.ec2.aws_iam_role_policy.ecr_access \
                        -target=module.ec2.aws_iam_instance_profile.ec2_profile \
                        -auto-approve

        # Apply all changes including new EC2
        terraform apply -auto-approve

    - name: Terraform Destroy
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy_infra'
      env:
        TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      run: terraform destroy -auto-approve -input=false

